"""Export services: PowerPoint, PDF, Markdown generation."""
from __future__ import annotations

import io
import json
import logging
from typing import Any

log = logging.getLogger(__name__)


def generate_pptx(brief: dict[str, Any]) -> bytes:
    """Generate a PowerPoint presentation from a brief."""
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.enum.text import PP_ALIGN

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    title_layout = prs.slide_layouts[0]
    content_layout = prs.slide_layouts[1]
    blank_layout = prs.slide_layouts[6]

    # Title slide
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = brief.get("title", "Macroeconomic Brief")
    if slide.placeholders[1]:
        slide.placeholders[1].text = brief.get("subtitle", "Generated by Macro Brief AI")

    content = brief.get("content", {})
    sections = content.get("sections", [])

    for section in sections:
        slide = prs.slides.add_slide(content_layout)
        slide.shapes.title.text = section.get("title", "")

        body = slide.placeholders[1] if len(slide.placeholders) > 1 else None
        if body:
            tf = body.text_frame
            tf.clear()

            text = section.get("text", "")
            bullets = section.get("bullets", [])

            if text:
                p = tf.paragraphs[0]
                p.text = text
                p.font.size = Pt(14)

            for bullet in bullets:
                p = tf.add_paragraph()
                p.text = bullet
                p.font.size = Pt(12)
                p.level = 0

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf.read()


def generate_markdown(brief: dict[str, Any]) -> str:
    """Generate a Markdown document from a brief."""
    lines = [f"# {brief.get('title', 'Macroeconomic Brief')}\n"]

    content = brief.get("content", {})
    sections = content.get("sections", [])

    for section in sections:
        lines.append(f"\n## {section.get('title', '')}\n")
        text = section.get("text", "")
        if text:
            lines.append(f"{text}\n")
        for bullet in section.get("bullets", []):
            lines.append(f"- {bullet}")

    return "\n".join(lines)


def brief_to_export_format(brief_data: dict[str, Any], fmt: str = "pptx") -> tuple[bytes | str, str]:
    """Convert brief data to the requested format.

    Returns (content, mime_type).
    """
    if fmt == "pptx":
        return generate_pptx(brief_data), "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    elif fmt == "markdown":
        return generate_markdown(brief_data), "text/markdown"
    elif fmt == "json":
        return json.dumps(brief_data, indent=2, default=str), "application/json"
    else:
        raise ValueError(f"Unsupported format: {fmt}")
